name = "mdgen"
compatibility_date = "2025-04-03"

[assets]
not_found_handling = "single-page-application"

[site.headers]
"/*.js" = { Cache-Control = "public, max-age=31536000, immutable" }
"/*.css" = { Cache-Control = "public, max-age=31536000, immutable" }
"/*.svg" = { Cache-Control = "public, max-age=31536000, immutable" }
